### ISSUE TITLE
Chapter 6 - CUDA goes out of memory even with batch size 4.

### ISSUE THREAD

**Issue by praveenr2998** [PacktPublishing/PyTorch-Computer-Vision-Cookbook#11]
I am not sure why but even with batch size 4 CUDA goes out of memory, i think many unwanted things(like gradients)are kept in memory so memory is insufficient. I have 6 GB memory, can you alter the code to clear unwanted things out of memory and make the code even more efficient.

Even i tried in kaggle kernel and again CUDA goes out of memory.

**Comment by mave5** [comment]
Is this for chapter 6: Single-Object Segmentation? 
I cannot recall the "out of memory message" for Chapter 6 since the model and data are pretty light.
At what stage did you get the error?

**Comment by praveenr2998** [comment]
Yes 6th chapter. While training as i have 6GB CUDA goes out of memory after 26 epochs, then i used kaggle kernel they have 15GB and CUDA went out of memory after 72 epochs.

**Comment by mave5** [comment]
My guess is that the error is due these two lines
```python
    pred= torch.sigmoid(output)
    _, metric_b=dice_loss(pred, target)
```
inside ```loss_batch``` helper function. They calculate the dice metric during training. 

Can you try one of these two options:
- comment out the two lines and return a fixed number for ```metric_b```  for now to see if that is causing the error
- put the two lines under ```with torch.no_grad():``` to avoid tracking gradients when calculating the metric.

**Comment by praveenr2998** [comment]
Thank you, 
i used "with torch.no_grad():" and it works perfectly.
Thank you very much.
